title:        PSAS
tagline:      Rockets
description:  Rockets
canonical:    http://psas.pdx.edu
url:          ''

# Owner/author information
owner:
  name:           Portland State Aerpospace Society
  avatar:         avatar.png
  bio:            "Rockets"
  email:          info@psas.pdx.edu
  twitter:        pdxaerospace
  github:         psas
  youtube:        PSASRockets
  location:       "Portland, Ore"

exclude: ['Makefile', 'README.markdown']

timezone:    America/Los_Angeles
future:      true
markdown:    kramdown
kramdown:
  toc_levels: "2,3"

sass:
    style: :compressed

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Get Involved
    url: /join/
  - title: Launches
    url: /launches/
  - title: Projects
    url: /projects/
  - title: Rockets
    url: /rockets/
